### PR TITLE
plugins: modify the git plugin to support atomic commits

### PR DESCRIPTION
**Pull request by rismoney**
before: all package updates commited to git were stored in a
single commit

after: provide an argument for the git plugin called AtomicCommit.
This generates a unique commit message for each package that is
updated.

### CODE REVIEW

**Comment by majkinetor** [comment]
Isn't any commit by the bot new release ? Why do you need tags ?

**Comment by rismoney** [comment]
Because there could be non bot commits or non package related commits.

This is paramount to walking the gitlog.  Only tags get checked out and
built if you had to reconstitute a complete gallery/repo.

**Comment by majkinetor** [comment]
Those commits will not be done by bot. Filtering in the bot is the same filtering in the tags. Bulding against the tag is the same as building on bot commit.

Just click on the bot name in any AU repo and you will see.

The problem u mention exists only if u used ur email adress for git plugin.

**Comment by rismoney** [comment]
If the repo is a combination of automatic and manual updates, there is no
discernible way to only create nupkg files from intended releases.  Also
the ability to pull packages out from building necessitates tagging.
Perhaps you are not thinking about it from an enterprise repo vs.
chocolatey.org scenario.

I added this as an optional switch and thought it doesn't add complexity
unless user wants it.

**Comment by majkinetor** [comment]
> If the repo is a combination of automatic and manual updates, there is no discernible way to only create nupkg files from intended releases.

Not true, like I said, because by default automatic updates are done by different git user. [Here](https://github.com/majkinetor/au-packages/commits?author=choco-bot) are **only** automatic update of my repo. You can create nupkg files for each release. To get releases for single package, see its log history for specific user, for instance for my trid package here are last 5 releases:

```
master au-packages\trid~> git --no-pager log --author=Chocolatey -5 --pretty=oneline

0fb77e8c1a423ee98004e5814fd6341572ad2c86 (HEAD -> master, origin/master, origin/HEAD) AU: 2 updated - shutup10 trid [skip ci] https://gist.github.com/a700c70b8847b29ebb1c918d47ee4eb1/f4c265c9668a92a6dc8d29a521ebd8e7568cd1d5
05352350e95c4bbe7c97f2191187cf7daf7ed9c1 AU: 2 updated - shutup10 trid [skip ci] https://gist.github.com/a700c70b8847b29ebb1c918d47ee4eb1/47febf22aa798ecfd0d5a28bb9cf2f9922459941
cdf9e4bb6fe43bb458b7d95cf929b25df01c2f46 AU: 3 updated - rundeck smplayer trid [skip ci] https://gist.github.com/a700c70b8847b29ebb1c918d47ee4eb1/e41c1badef1473694687097fee5ccb60fac32816
f8c7ac18c0fe7c50b7d9c561f837ed9033b4b467 AU: 4 updated - dbeaver fzf nirlauncher trid [skip ci] https://gist.github.com/a700c70b8847b29ebb1c918d47ee4eb1/f765aad084b7dbc6c5f2064ba311fa5407405214
3a28157dd02a3b2581dd1f88168172a2129e5fed AU: 2 updated - rundeck trid [skip ci] https://gist.github.com/a700c70b8847b29ebb1c918d47ee4eb1/a2160e3d5eecbbaae8ee6625c9f85467921eb53e
```

> Perhaps you are not thinking about it from an enterprise repo vs. chocolatey.org scenario.

I don't make a difference really - If its not good for enterprise its not good for my private usage either. Majority of my work with choco is for enterprise and CI/CD pipelines.

I don't mind your PR at all except some design issues (I don't like 2 parameters where 1 would suffice), I am trying to understand what you gain that is not already possible. As far as I can see now there is nothing new you could do with this PR, it just makes it doable another way to achieve the same thing (i.e. a matter of preference rather then tech issue).

**Comment by rismoney** [comment]
> Not true, like I said, because by default automatic updates are done by different git user.

I can filter the commits by author like you did.  That is not the issue.
The issue is that I want to be able to filter commits based on valid releases.  Your example above filtered valid releases based on author chocolatey.  cool.  

Use case 1.
If one of those valid releases you later deem invalid.
Here, reverting doesn't help, because then you have further timeline issues.  The concept of latest is irrelevant.  This is about creating nupkg files.  I don't just want newest.  I want valid nupkgs.

Use case 2.
Outside of AU: rismoney could make different types of manual commits to a choco git pkg repo.  i edit a readme or i bump a nuspec version.  Now how do i filter?
I could do a git log --all '*.nuspec' but that assumes I want to build every single version of every package.  If there was a bad package in the timeline, like 3 years ago, where the url no longer exists, how do i now omit?

I found this to be the only reliable way to exclusively build only the _desired_ packages from a git log.

Example extracted mini script I open sourced  ~5 years ago demonstrating how to do something like this:
https://github.com/rismoney/chocolatey-git/blob/master/build.ps1

**Comment by rismoney** [comment]
> I don't mind your PR at all except some design issues (I don't like 2 parameters where 1 would suffice), 

I provided the granularity of allowing atomic commits and tagging.  They can certainly be unified into 1, but I feel as though some people may not care about the tagging, and just want itemized commits for auditability.  

The tagging is needed primarily for reconstitution, in say a DR scenario, where you were starting with nothing but a git clone of your package repo.

I hope this clarifies.

**Comment by rismoney** [comment]
Finally, the last point, is these are feature flags, that if the user doesn't explicitly use them, there is no behavioral change.

**Comment by majkinetor** [comment]
I can't follow the logic in your use case 1 & 2. Maybe I am just tired and can't dig it during this period or maybe our methodologies are different. I wonder how automatic tagging provides validity. There isn't any method to make a package valid, the best that can be done is to embed it.

> They can certainly be unified into 1, but I feel as though some people may not care about the tagging, and just want itemized commits for auditability.

I was thinking about 1 parameter, such as `Strategy`:

```powershell
[ValidateSet( 'single commit', 'commit per package', 'commit per package tagged')]
[string] Strategy = 'single commit'
```

Maybe some better wording tho...

**Comment by rismoney** [comment]
wrt tags - They simply are applied only to releases.  They eliminate the need to filter where filtering cannot discern.  By adding this to AU, keeps the behavior consistent for tagging releases when done manual via end users.  Repository updates, that are not package related don't get tagged.  Bad packages that are no longer needed, are tag deleted.  At any point in time, iteration of the tags will present all valid releases in the repo of all packages.

wrt stategy- i'm ok w/ that.  I thought the boolean flags `atomicupdate` `atomicupdatetagging` indicating what they actually did were more reasonable than `strategy`, with a validity set that is obscure.
I could have gone with `atomictagging` but that dissassociates from commit when its really a sub argument.

https://en.wikipedia.org/wiki/Atomic_commit

**Comment by rismoney** [comment]
here is a concrete example:
```
C:\gitrepos\chocopackages [oned =]> git tag -l
7zip-16.04.0.0
adobereader-2017.009.20044
chrome-57.0.2987.133
chrome-61.0.3163.100
```

Lets say i no longer want chrome-57.0.2987.133 to be generated.
```
git tag -d chrome-57.0.2987.1330
git push origin :chrome-57.0.2987.133
```

If I rely on git --no-pager log --author=Chocolatey -5 --pretty=oneline how do i omit the create of chrome 57?   At any given point in time, git tag -l shows me all the packages that are considered 'released'


tags are awesome.  you should use them!

**Comment by majkinetor** [comment]
I would probably use a function that allows exclusion of certain versions:

`function build-releases($Exclude='chrome-57.0.2987.1330', '...'){}`

Keeping it on repository would make it work for everybody.


But I see the merits of this now that you provided more concrete example. Thanks for patience. 

>  I thought the boolean flags atomicupdate atomicupdatetagging indicating what they actually did were more reasonable than strategy, with a validity set that is obscure.

Matter of knowledge I guess, it was not ringing a bell to me. But OK, I can live with that now that you provided wikipedia page :) Maybe combination: 

```
[ValidateSet( 'single', 'atomic', 'atomictag')]
[string] Strategy = 'single commit'
```

Looks beteter within update options I think.

**Comment by rismoney** [comment]
Ok, Then it should be called commitStrategy to better convey.  Strategy feels opaque.

**Pull request merged**
