### PR TITLE
Streams support

### PR DESCRIPTION
**Pull request by Thilas**
As discussed in #92, here is an attempt to bring streams support to AU according to a solution mentions in #74.

Basically, I have refactored the existing code and created a method `process_stream` that do the same thing as it used to but for each provided stream. Of course, existing packages are still working.

And in order to improve how AU deals with version numbers (especially for version sorting), I also introduced an `AUVersion` class. Additionally, it can be very helpful as well for AU automatic package creation when parsing versions from vendors web sites.

To illustrate all this, I started using this on my own packages and especially on 2 of them that required streams support: atom & strawberryperl (https://github.com/Thilas/chocolatey-packages/tree/streams).

Let me know if you have any questions about my changes. Thank you!

### CODE REVIEW

**Comment by majkinetor** [comment]
Thanks @Thilas .

I looked into it and it looks OK.  Let me play with it for some time. There are quite a lot of changes here so it will require time. I would also like to use it for some time around and on coreteamrepository and that requires separate AU branch which can be then activated within appveyor.yml.

Pester tests for streams and Get-Version are also required before this can pass. Related to version, Posh6 has [SemanticVersion] negatively so I didn't want to that but wait, but your variant is more flexible.

**Comment by majkinetor** [comment]
I created streams branch where this one should be merged.

**Comment by Thilas** [comment]
I was so focused on my own tests that I forgot to add proper unit tests on the repo. I'll push some later today. Otherwise, let me know if I can help you with your tests.

**Comment by Thilas** [comment]
Here are Pester tests for class AUVersion + some a couple of fixes for existing tests. I still working on tests on streams. I'll let you know.

**Comment by Thilas** [comment]
@majkinetor, I'm done adding tests. Let me know if you have any remarks.

**Comment by majkinetor** [comment]
Just PR everything to AU streams branch instead of master.

**Comment by Thilas** [comment]
Done.

**Comment by majkinetor** [comment]
Great, thx. If you feel need to add anything else PR to this branch again. I will be testing this on my own repo for some time.

**Pull request merged**
