### PR TITLE
Fixed help text to display switch or variable

### PR DESCRIPTION
**Pull request by pauby**
Fixed help text to display -NoCheckChocoVersion switch or $au_NoCheckChocoVersion variable

### CODE REVIEW

**Comment by majkinetor** [comment]
I am not sure this is helpful. Makes a text very long and it may break some Pester tests.
Everything is explained in the https://github.com/majkinetor/au#global-variables

**Comment by pauby** [comment]
The current help text suggests setting variable $NoCheckChocoVersion which is misleading. Setting that variable makes no difference. It caused me around an hour of frustration before I went into the code and discovered it was a switch. My suggestion is simply to clarify the help message so it is correct and remove the misleading name.

Regardless of what is in the wiki docs, the help message in the code says to use a variable that is incorrect.

**Comment by majkinetor** [comment]
There are strings in tests, see for example: 

https://github.com/majkinetor/au/blob/8df529c915f73b446900997e0ebf24760d93e081/tests/Update-Package.Tests.ps1#L176

although it would not break it as it contains first part of the message.

**Comment by pauby** [comment]
I'm struggling to understand why the preference is to leave the existing tests unchanged and keep a message that (in my opinion) is misleading rather than just change the tests. The priority (for me) would be to have the message be clearer and deal with making that happen.

**Pull request closed without merging**
