### PR TITLE
Display actual errors from jobs when any

### PR DESCRIPTION
**Pull request by Thilas**
@majkinetor, I just noticed that when running updateall script we never get the actual errors from the powershell jobs running update scripts. Here is a change that aims at fixing this behavior.

FYI, I basically applied the solution from https://stackoverflow.com/questions/8751187/how-to-capture-the-exception-raised-in-the-scriptblock-of-start-job

Any thoughts?

### CODE REVIEW

**Comment by majkinetor** [comment]
That is regression explained here: https://github.com/majkinetor/au/issues/181

Will need to check it out, in that part of code subtle errors can creep in...

**Comment by majkinetor** [comment]
I left this unsolved because I wanted to understand why did this happen with that change in #181. I did read the code many times and tested various versions but still not sure why ... throwing is obviously solution instead of return but that part of code worked before .... When I revert #181 it works again...

**Comment by majkinetor** [comment]
Looks OK, lets merge and check out tests.

**Comment by Thilas** [comment]
Thanks! Let me know if you see anything wrong with this. I'll have a look.

**Pull request merged**
