### PR TITLE
Reportplugin

### LINKED ISSUE #244: Report plugin links to update_all with a hard-coded branch name
Here's an example:
https://gist.github.com/jack1142/4a1ffb06ffe2a5216cb65b16ebe279df
image

It works fine because I used GitHub's rename feature and therefore have a redirect from master to main but this wouldn't work for new repositories or people who didn't use this feature.

### LINKED ISSUE #257: Report plugin has hard coded links
This issue is similar to #244, but a little more broad than just a hard coded "branch".  In my scenario, I would like to use AU to automate updates for a private repository.

* I'm attempting to get things working on a repository that is hosted on a Gitlab server, so the link generated for the Update_all script is broken.  (Could be handled with a variable.)
* Also the links to packages assume `https://chocolatey.org` in the markdown table, so doesn't work for a private internal repo whose packages may not always have corresponding packages on Chocolatey.org.  (The `$au_GalleryPackageRootUrl` variable could probably be used to address this.)

Does it make sense to fix this in the report plugin that comes with AU?  Or do people normally write all custom plugins for a scenario like this?

(I would be happy to work on a pull request, if it makes sense to address this in the built-in AU plugin.)

### PR DESCRIPTION
**Pull request by danmetzler**
Closes #257 

* Adds `Package_Source_Root_Url` param to Markdown report type param in Report and also in History plugin
  * People can add this to Update_All.ps1 script, and typically feed it an environment variable.
  * `$Package_Source_Root_Url` defaults to `https://github.com/$Github_UserRepo` if not specified.
* Links to packages in report are derived from $au_GalleryPackageRootUrl instead of hardcoded to `https://chocolatey.org/packages`
  * `$au_GalleryPackageRootUrl` defaults to `https://chocolatey.org/packages` if not specified.
  * Note: `$au_GalleryPackageRootUrl` was added to Update-Package.ps1 in previous commit e6d806e67eb337031df4d5629ddeed67c3a4a67b.  This adds it to md_table function to generate the links to the package there in Markdown report.

Closes #244

* Adds `Package_Source_Branch` param to Markdown report type param in Report plugin.
  * Defaults to `master` if not specified.
  * Typically this would be fed an environment variable,  if needed.

Regarding #258 commit e14bb595528458bb585888c2ef610bd7e75fc1eb

* In History plugin, `--no-merges` was added before the `log` command in the `git log` command.  Caused git to complain about unrecognized option.  I moved `--no-merges` after the `log` command and then it works fine. 

All of this works in my environment now, and passes existing tests.

### CODE REVIEW

**Comment by majkinetor** [comment]
Just change the name of the params - there are no params with underscores now.

**Comment by majkinetor** [comment]
Also, u should add PR to the au-template later with those new options and comment next to it.

**Comment by danmetzler** [comment]
Renamed params:

* Package_Source_Root_Url is now PackageSourceRootUrl
* Package_Source_Branch is now PackageSourceBranch

(I think that's what you meant, right?)

**Comment by danmetzler** [comment]
> Also, u should add PR to the au-template later with those new options and comment next to it.

I will take a look at the template, and work up a pull request.

**Comment by majkinetor** [comment]
On a second thought dont do that.

**Comment by danmetzler** [comment]
> On a second thought dont do that.

ok

**Comment by majkinetor** [comment]
Yeah, I don't want to pile up params there that are probably going to be used rarely.

**Pull request merged**
