### PR TITLE
Git plugin: create branch if it does not exist

### PR DESCRIPTION
**Pull request by easybe**
Note that if a local branch with the same name already exist, it will be reset to the current HEAD.

### CODE REVIEW

**Comment by majkinetor** [comment]
Why would we need flag for this ? Can't you just create a branch if it doesn't exist by default ?

**Comment by easybe** [comment]
Yes, I guess that could work for me.

However,

https://github.com/majkinetor/au/blob/cb04813aa1a5e6dffed4d762ef487f8affe86c47/AU/Plugins/Git.ps1#L56

is also a problem for me. IMHO a `git pull` does not really make sense here, as we have uncommitted changes at this point which will lead to an error. Or am I missing something here?

Is it an option to change the current behavior?

**Comment by majkinetor** [comment]
That is for collaborative environment where somebody else might push to that branch in the middle of the CI pipeline. It ensures there are no conflicts on push.

**Comment by majkinetor** [comment]
That is also not a problem, you could ignore error on it do it for existing branches only.

**Comment by easybe** [comment]
OK, I updated the PR.

> Note that if a local branch with the same name already exist, it will be reset to the current HEAD.

I hope that is OK.

**Comment by majkinetor** [comment]
You miss `-q` everywhere. Without it CI may fail.

**Comment by easybe** [comment]
> You miss `-q` everywhere. Without it CI may fail.

I would prefer it that way, but OK, I can add it.

**Comment by easybe** [comment]
Done

**Comment by majkinetor** [comment]
I would prefer it too, but CI fails because git writes to stderr if q is not present.

**Comment by majkinetor** [comment]
So with this change, you can basically make persistence commits visible in separate branch and not pollute your master branch with bot commits ? Its enough for me to set some arbitrary non existent branch like `-Branch updatebot` ?

**Comment by easybe** [comment]
Yes, exactly. I create PRs from these branches.

**Comment by majkinetor** [comment]
So, are you done and check if it works in real AU update ? This plugin is used by everybody.

**Comment by easybe** [comment]
Yes, I am done.

It works in my set up which is based on https://github.com/majkinetor/au-packages-template/blob/master/update_all.ps1.

Not sure how to test it more.

**Comment by majkinetor** [comment]
Ah, wait...  It won't work like this I think. If packages are on master and you are pulling `updatebot` you will get nothing. So you need to get master and switch to another branch after that if I am not mistaken.

**Comment by easybe** [comment]
For me it works because:

* CI checks out master
* AU creates a new branch from master
* AU pushes that to the branch
* You can merge branch into master

That is why the "pull" does not make sense to me...

**Comment by easybe** [comment]
If you specify `master` as the branch, nothing should have changed.

**Comment by majkinetor** [comment]
It was there as  a safety because time passes since CI pulls the master and AU finishes and your changes are "saved". If anybody commits during that time you can't push on the same branch any more. Contrary to that, pull immediately before commit makes that highly unlikely. 

Now it works for you because of your specific setup. It may not work for people who use the same branch for source and destination and have more active users. 

So, 

1. CI checks out the latest master
2. CI script runs init
3. CI scripts runs AU
4. AU runs for some time
5. Somebody commits on master   <========= THIS 
6. AU finishes 
7. AU tries to push to master and fails.

**Comment by majkinetor** [comment]
In case Branch is different then master, then I agree, pull is probably not needed UNLESS again somebody commits to it, like you have multiple AU scripts for some reason operating for redundancy.

**Comment by majkinetor** [comment]
Other problem is that you don't need to have CI - you can perfectly have Git plugin working without any CI whatsoever, then it needs to pull master if AU runs from 2 locations .

**Comment by majkinetor** [comment]
So maybe to be sure, we should have 2 params, SourceBranch aka Branch as before (param alias) and DestinationBranch. If you use CI and you are lone developer you could probably just use DestinationBranch and CI will do the rest.

**Comment by easybe** [comment]
I really don't see any problem. As I said, 

> If you specify master as the branch, nothing should have changed.

because a `git pull` is still performed.

If you use a different branch, worst case would be that you have a merge conflict when merging the branch. Then you can either re-run or rebase.

**Comment by easybe** [comment]
If you have two AU scripts pushing to the same branch, the slower one will pull the newly created branch.

**Comment by easybe** [comment]
I like this solution because the changes are very minimal 🤷‍♂️

**Comment by majkinetor** [comment]
It works on my repo, branch name `updates`

- https://ci.appveyor.com/project/majkinetor/au-packages/builds/39416572#L200
- https://github.com/majkinetor/au-packages/commits/updates

Not sure why it triggered new build ASAP after bot commit on AppVeyor ... need to look into it.

**Pull request merged**
